### ISSUE TITLE
Multiple duration tags always results in no duration displayed

### ISSUE THREAD

**Issue by rugbyopera** [iymeko/strategitica#52]
When a single task has more than one [strategitica|duration|...] applied, Strategitica always ignores the durations, even when the durations all match.

How to recreate:
1. Create two tags in Habitica that both have the same [strategitica|duration|...] on them. Mine happened to be  [strategitica|duration|00:01].
2. Apply both tags to the same task.
3. Load Strategitica. Find the task. No duration shows.

It makes sense to ignore when the [duration] labels conflict each other. If one tag says duration|00:01 and the other says duration|04:32, yeah, ignore them both. But if the labels all agree that duration should be 00:01, rely on that info.

**Comment by iymeko** [comment]
I didn't consider users having more than one tag with the same duration but it shouldn't be much trouble to implement this. Thanks for making the issue 🙂
