### ISSUE TITLE
Never due task showing in calendar

### ISSUE THREAD

**Issue by iymeko** [iymeko/strategitica#53]
> Hmm, it has decided one of my never-due tasks is due on Saturdays, though. 0_o

_Originally posted by @citrusella in https://github.com/iymeko/strategitica/issues/44#issuecomment-834470223_

**Comment by citrusella** [comment]
For some context:

The settings for the daily on Habitica (it's a task I use solely to divide up my task list, and it's the only one having an issue) are "weekly" every 1 weeks with all days unchecked. Strategitica seems to understand this if I open the edit form (the settings look right), but the task modal popup thing when clicking it just to view says "every on the 25th" or something to that effect (its start date is a 25th of a month back in 2017). It's showing on every Saturday on the calendar--not even on a 25th. No other task that are like that one are appearing to show up on days they're not due.

**Comment by iymeko** [comment]
> "weekly" every 1 weeks with all days unchecked. Strategitica seems to understand this if I open the edit form (the settings look right), but the task modal popup thing when clicking it just to view says "every on the 25th" or something to that effect (its start date is a 25th of a month back in 2017).

Thank you for the extra info. Yeah, I don't think I set it up to consider that maybe none of the day of the week checkboxes would be checked. I'll have to accommodate for that.

> It's showing on every Saturday on the calendar--not even on a 25th. No other task that are like that one are appearing to show up on days they're not due.

Weird, I'll look into why it'd be doing that.
